Global:
  model_dir: ./yolov5s.onnx
  format: 'onnx'
  model_filename: model.pdmodel
  params_filename: model.pdiparams
  image_path: ./COCO_val_320
  arch: YOLOv5

Distillation:
  alpha: 1.0
  loss: soft_label

Quantization:
  onnx_format: true
  use_pact: true
  activation_quantize_type: 'moving_average_abs_max'
  quantize_op_types:
  - conv2d
  - depthwise_conv2d


PTQ:
  calibration_method: 'avg'   # option: avg, abs_max, hist, KL, mse
  skip_tensor_list: None

TrainConfig:
  train_iter: 3000
  learning_rate: 0.00001
  optimizer_builder:
    optimizer:
      type: SGD
    weight_decay: 4.0e-05
  target_metric: 0.365
