mean:
  -
    - 127.5
    - 127.5
    - 127.5
std:
  -
    - 127.5
    - 127.5
    - 127.5
model_path: ./picodet_s_416_coco_lcnet/picodet_s_416_coco_lcnet.onnx
outputs_nodes: []
do_quantization: False
dataset:
output_folder: "./Portrait_PP_HumanSegV2_Lite_256x144_infer"
