Global:
  model_dir: ./MobileNetV3_large_x1_0_ssld_infer/
  format: 'paddle'
  model_filename: inference.pdmodel
  params_filename: inference.pdiparams
  qat_image_path: ./ImageNet_val_640
  ptq_image_path: ./ImageNet_val_640
  input_list: ['inputs']
  qat_preprocess: cls_image_preprocess
  ptq_preprocess: cls_image_preprocess
  qat_batch_size: 128


Distillation:
  alpha: 1.0
  loss: soft_label

QuantAware:
  use_pact: true
  activation_bits: 8
  is_full_quantize: false
  onnx_format: True
  activation_quantize_type: moving_average_abs_max
  weight_quantize_type: channel_wise_abs_max
  not_quant_pattern:
  - skip_quant
  quantize_op_types:
  - conv2d
  - depthwise_conv2d
  - matmul
  - matmul_v2
  weight_bits: 8

TrainConfig:
  epochs: 2
  eval_iter: 5000
  learning_rate: 0.001
  optimizer_builder:
    optimizer:
      type: Momentum
    weight_decay: 0.00002
  origin_metric: 0.7896

PTQ:
  calibration_method: 'avg'   # option: avg, abs_max, hist, KL, mse
  skip_tensor_list: None
