Global:
  model_dir: ./MobileNetV1_ssld_infer/
  format: 'paddle'
  model_filename: inference.pdmodel
  params_filename: inference.pdiparams
  qat_image_path: ./ImageNet_val_640
  ptq_image_path: ./ImageNet_val_640
  input_list: ['input']
  qat_preprocess: cls_image_preprocess
  ptq_preprocess: cls_image_preprocess
  qat_batch_size: 32

Distillation:
  alpha: 1.0
  loss: l2
  node:
  - softmax_0.tmp_0


Quantization:
  use_pact: true
  activation_bits: 8
  is_full_quantize: false
  onnx_format: True
  activation_quantize_type: moving_average_abs_max
  weight_quantize_type: channel_wise_abs_max
  not_quant_pattern:
  - skip_quant
  quantize_op_types:
  - conv2d
  - depthwise_conv2d
  weight_bits: 8


TrainConfig:
  train_iter: 5000
  learning_rate:
    type: CosineAnnealingDecay
    learning_rate: 0.015
    T_max: 8000
  optimizer_builder:
    optimizer:
      type: Momentum
    weight_decay: 0.00002
  origin_metric: 0.70898


PTQ:
  calibration_method: 'avg'   # option: avg, abs_max, hist, KL, mse
  skip_tensor_list: None
