Global:
  model_dir: ./ppyoloe_crn_l_300e_coco
  format: paddle
  model_filename: model.pdmodel
  params_filename: model.pdiparams
  image_path: ./COCO_val_320
  arch: PPYOLOE
  input_list: ['image','scale_factor']
  preprocess: ppdet_image_preprocess

Distillation:
  alpha: 1.0
  loss: soft_label

Quantization:
  onnx_format: true
  use_pact: true
  activation_quantize_type: 'moving_average_abs_max'
  quantize_op_types:
  - conv2d
  - depthwise_conv2d


PTQ:
  calibration_method: 'avg'   # option: avg, abs_max, hist, KL, mse
  skip_tensor_list: None

TrainConfig:
  train_iter: 5000
  learning_rate:
    type: CosineAnnealingDecay
    learning_rate: 0.00003
    T_max: 6000
  optimizer_builder:
    optimizer:
      type: SGD
    weight_decay: 4.0e-05
